name: 'Setup GitHub SSH'
description: 'Configures SSH access for GitHub repositories'

inputs:
  ssh-private-key:
    description: 'SSH private key for GitHub authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure SSH for GitHub
      shell: bash
      run: |
        # Create the .ssh directory if it doesn't exist
        mkdir -p ~/.ssh

        # Write the SSH private key to a file
        echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_rsa

        # Set proper permissions for the private key file
        chmod 600 ~/.ssh/id_rsa

        # Add the host's SSH key to the known hosts file
        ssh-keyscan 'github.com' >> ~/.ssh/known_hosts 