name: 'Setup Git Authentication'
description: 'Configure Git authentication for GitHub repositories and submodules'

inputs:
  token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Git authentication
      shell: bash
      env:
        GIT_TOKEN: ${{ inputs.token }}
      run: |
        echo "Setting up Git authentication..."
        
        # Set GIT_ASKPASS to handle Git authentication
        export GIT_ASKPASS=/tmp/.git-askpass
        echo 'echo $GIT_TOKEN' > $GIT_ASKPASS
        chmod +x $GIT_ASKPASS
        
        # Configure Git to use HTTPS with the token
        git config --global url."https://github.com/".insteadOf "https://github.com/"
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git config --global url."https://github.com/".insteadOf "ssh://git@github.com"
        
        echo "Git authentication configured successfully"
