name: Build ubuntu cache from main branch to make it available to every other workflow
# https://github.com/actions/cache/blob/main/tips-and-workarounds.md#use-cache-across-feature-branches
# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version for compiling'
        required: true
        type: string
      node-version:
        description: 'Node version for compiling'
        required: true
        type: string
      ruby-version:
        description: 'Ruby version for compiling'
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the cache on ubuntu for app building
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Ruby and install Gems with cache
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}
          bundler-cache: true

      - name: Set NPM registry
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.org
          scope: '@taxdown'
          cache: 'yarn'

      - name: Install NPM dependencies
        run: yarn install --frozen-lockfile --network-timeout 600000
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up Java version for sdkmanager
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
          cache: 'gradle'

      - name: Install Gradle dependencies
        run: bundle exec fastlane android install_dependencies
