name: Handle npm package CI from shared workflow npm-package

on:
  workflow_call

jobs:
  build:
    name: Build npm package and run tests 🔨
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Set NPM registry
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          registry-url: https://registry.npmjs.org
          scope: '@taxdown'

      - name: Installing clean NPM dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run build application
        run: npm run build

      - name: Run tests
        run: npm run test
  deploy:
    name: Deploy npm package 🚀
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Set NPM registry
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          registry-url: https://registry.npmjs.org
          scope: '@taxdown'

      - name: Installing NPM dependencies on production mode
        run: npm install --production
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run build application
        run: npm run build

      - name: Publish NPM package
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}