name: Ensure PR is compliant with taxdown's guidelines ✅

on: workflow_call

jobs:
  prepare:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      # Version is locked down since we are sharing GITHUB_TOKEN, which is a secret
      # before changing this action's version, ensure no malicious code is executed
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # https://www.conventionalcommits.org/en/v1.0.0/#specification
          types: |
            feat
            fix
            build
            chore
            ci
            docs
            style
            refactor
            perf
            test
          scopes: |
            core
            deps
            deps-dev
            main
            master
            ui
          requireScope: false
          # This example ensures the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
          wip: false
