name: Ensure PR is compliant with taxdown's guidelines ✅

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            docs
            feat
            fix
            perf
            refactor
            style
            test
          scopes: |
            core
            deps
            ui
          requireScope: false
          # This example ensures the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
          wip: false
